version: '3'
services:
  withings-exporter:
    image: nginx:stable
    container_name: withings-exporter
    volumes:
      - ./public:/usr/share/nginx/html:ro
    ports:
      - 9101:80
    restart: always
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100
    restart: always
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - 3000:3000
    restart: always
