[project]
name = "withings-exporter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "prometheus-client>=0.21.1",
    "pyyaml>=6.0.2",
    "withings-api>=2.4.0",
]
