name: Upload Withings prom data

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nanasess/setup-chromedriver@v1.0.5
    - name: Install pipenv
      run: pipx install pipenv
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        cache: pipenv
    - name: Install dependencies
      run: pipenv install
    - name: Install Japanese Fonts
      run: |
        sudo apt install -y fonts-ipafont
        fc-cache -fv
        fc-list | grep -i ipa
    - name: Start XVFB
      run: Xvfb :99 &
    - name: Run Gathering Withings Data
      run: pipenv run main
      env:
        DISPLAY: :99
        WITHINGS_EMAIL: ${{ secrets.WITHINGS_EMAIL }}
        WITHINGS_PASSWORD: ${{ secrets.WITHINGS_PASSWORD }}
        WITHINGS_CLIENT_ID: ${{ secrets.WITHINGS_CLIENT_ID }}
        WITHINGS_CONSUMER_SECRET: ${{ secrets.WITHINGS_CONSUMER_SECRET }}
        WITHINGS_CALLBACK_URI: ${{ secrets.WITHINGS_CALLBACK_URI }}
        TZ: ${{ secrets.TZ }}
    - name: setup GCP Auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: setup GCP project information
      uses: google-github-actions/setup-gcloud@v0
    - name: Upload JSON to GCS
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: ./container/public/withings.prom
        destination: ${{ secrets.BUCKET_NAME }}/
    - name: Update Prometheus Data in RaspberryPi
      uses: benc-uk/workflow-dispatch@v1
      with:
        repo: legnoh/life-metrics-grafana-deployment
        ref: refs/heads/main
        workflow: Get Latest Metrics Data from GCS
        token: ${{ secrets.PERSONAL_TOKEN }}
